### ISSUE TITLE
> * 同底数幂的乘法

### ISSUE THREAD

**Issue by dangming25** [mathedu4all/mathcrowd-community#11]
> * 同底数幂的乘法
> * 幂的乘方
> * 积的乘方

是否与“数与运算板块”重复？

_Originally posted by @mathedu4all in https://github.com/mathedu4all/mathcrowd-community/issues/6#issuecomment-62126519
应该不会重复，这部分内若更多的是式的运算

**Comment by mathedu4all** [comment]
好的
