### ISSUE TITLE
> 方程与方程的解

### ISSUE THREAD

**Issue by dangming25** [mathedu4all/mathcrowd-community#12]
> 方程与方程的解
> 
> * 列方程
> * 方程的解

这个不应该放在一元一次方程下级吧～

_Originally posted by @mathedu4all in https://github.com/mathedu4all/mathcrowd-community/issues/6#issuecomment-621266538_
这部分内容主要是有一个方程的概念，然后解的概念，一元一次是强调一元一次方程的概念，所以会有些区别

**Comment by mathedu4all** [comment]
但是单独考察概念的题多吗？教师是否有需求单独找出只考概念不考解法的题？

**Comment by mathedu4all** [comment]
目前“方程与方程的解”在一元一次方程下面？这块内容是强调方程的解的概念吧，应该是通用所有方程的？

**Comment by dangming25** [comment]
理论上是这样的，但是在实际的教学中会单独拉出来讲，又会在每一种方程的下面会单独再次强调这个部分的内容

**Comment by mathedu4all** [comment]
好的，知识点体系还是以数学分支为参考～
