### ISSUE TITLE
确立知识点树状结构

### ISSUE THREAD

**Issue by mathedu4all** [mathedu4all/mathcrowd-community#3]
确立数学知识点的树状结构，即一、二级知识点.

* 方程与代数
  * 代数式
  * 集合
  * 逻辑
  * 数列
  * 方程(组)
  * 不等式
  * 三角恒等式
  * 线性代数
  * 数论

* 函数与分析
  * 函数基础
  * 初等函数
  * 其他特殊函数
  * 微积分
  * 复分析

* 图形与几何
  * 解析几何
  * 向量几何
  * 欧式几何
  * 三角学

* 应用数学与数学文化
  * 算法
  * 组合计数
  * 概率与统计
  * 最优化问题
  * 数学应用题
  * 数学史
  * 数学思想方法
  * 常用数学方法

* 数与运算
  * 整数及其运算
  * 有理数及其运算
  * 实数及其运算
  * 复数及其运算
  * 指数运算及其性质
  * 对数运算及其性质

**Comment by mathedu4all** [comment]
# 高中数学

* 方程与代数
  * 集合
  * 逻辑
  * 不等式
  * 矩阵与行列式
  * 数列
  * 算法
  * 数论

* 函数与分析
  * 函数基础
  * 三角函数与反三角函数
  * 指数函数
  * 对数函数
  * 幂函数与多项式函数
  * 其他特殊函数

* 图形与几何
  * 解析几何
  * 立体几何
  * 向量几何

* 应用数学与数学建模
  * 组合计数
  * 概率与统计
  * 最优化问题

* 数与运算
  * 复数

**Comment by ghost** [comment]
1. 在方程与代数里应该添加上
- 平面向量
- 数系的扩充与复数；
2. 推理与证明应该也添加进去，不确定是否应该添加到**应用数学与数学建模**；
3. 一级知识点是否应该添加**数学史**

**Comment by ctdhm1984** [comment]
图形与几何是否可以添加**基本几何图形的定义与性质**

**Comment by mathedu4all** [comment]
> 图形与几何是否可以添加**基本几何图形的定义与性质**

这个作为欧式几何下面的三级知识点吧～

**Comment by mathedu4all** [comment]
> 1. 在方程与代数里应该添加上
> 
> * 平面向量
> * 数系的扩充与复数；
> 
> 1. 推理与证明应该也添加进去，不确定是否应该添加到**应用数学与数学建模**；
> 2. 一级知识点是否应该添加**数学史**

平面向量作为向量几何下的三级知识点是否更合适些.

数系扩张与复数感觉不太像知识点，可以分割为数学史和复数及其运算吧～

推理与证明，感觉也不太像知识点. 可以作为数学思想方法放在应用数学与数学文化下面吧～

数学史已添加为二级知识点在应用数学与数学文化下~

**Comment by ghost** [comment]
我们这里知识点最多三级吗？如果是这样，几何与图形下面的三级知识点就太多了。

> > 图形与几何是否可以添加**基本几何图形的定义与性质**
> 
> 这个作为欧式几何下面的三级知识点吧～

**Comment by mathedu4all** [comment]
> 我们这里知识点最多三级吗？如果是这样，几何与图形下面的三级知识点就太多了。
> 
> > > 图形与几何是否可以添加**基本几何图形的定义与性质**
> > 
> > 
> > 这个作为欧式几何下面的三级知识点吧～

理论上可以无穷多级哦～

**Comment by ctdhm1984** [comment]
> > 图形与几何是否可以添加**基本几何图形的定义与性质**
> 
> 这个作为欧式几何下面的三级知识点吧～

几何体的定义不一定在欧氏框架下，比如椭圆有斜率积定义就属于解析几何范畴，感觉独立出来作为一级会比较好

**Comment by ghost** [comment]
> > 1. 在方程与代数里应该添加上
> > 
> > 
> > * 平面向量
> > * 数系的扩充与复数；
> > 
> > 
> > 1. 推理与证明应该也添加进去，不确定是否应该添加到**应用数学与数学建模**；
> > 2. 一级知识点是否应该添加**数学史**
> 
> 平面向量作为向量几何下的三级知识点是否更合适些.
> 
> 数系扩张与复数感觉不太像知识点，可以分割为数学史和复数及其运算吧～
> 
> 推理与证明，感觉也不太像知识点. 可以作为数学思想方法放在应用数学与数学文化下面吧～
> 
> 数学史已添加为二级知识点在应用数学与数学文化下~

可以的。

**Comment by mathedu4all** [comment]
> > > 图形与几何是否可以添加**基本几何图形的定义与性质**
> > 
> > 
> > 这个作为欧式几何下面的三级知识点吧～
> 
> 几何体的定义不一定在欧氏框架下，比如椭圆有斜率积定义就属于解析几何范畴，感觉独立出来作为一级会比较好

有道理，所以椭圆方程、椭圆的第三定义是放在解析几何. 椭圆的第二定义在欧式几何下面？单独把基本图形和几何体弄出来感觉会很混乱吧～

**Comment by ctdhm1984** [comment]
> > > > 图形与几何是否可以添加**基本几何图形的定义与性质**
> > > 
> > > 
> > > 这个作为欧式几何下面的三级知识点吧～
> > 
> > 
> > 几何体的定义不一定在欧氏框架下，比如椭圆有斜率积定义就属于解析几何范畴，感觉独立出来作为一级会比较好
> 
> 有道理，所以椭圆方程、椭圆的第三定义是放在解析几何. 椭圆的第二定义在欧式几何下面？单独把基本图形和几何体弄出来感觉会很混乱吧～

这样确实比较合理，按照工具框架对定义进行区分

**Comment by ghost** [comment]
Chrome浏览器有个插件**MathJax Plugin for Github**可以显示GitHub上的数学公式😁。

**Comment by mathedu4all** [comment]
> Chrome浏览器有个插件**MathJax Plugin for Github**可以显示GitHub上的数学公式。

我尝试安装了显示出错，不过还是不建议这么干吧～完全可以用github.io
