### ISSUE TITLE
删除知识点

### ISSUE THREAD

**Issue by dangming25** [mathedu4all/mathcrowd-community#34]
旧初中知识点中有：换元法，反证法，组合体，程序语句，路程速度，火车过桥，鸡兔同笼等问题，已标红，建议删除。

换元法，反证法，这部分问题针对性不强，很多知识点都有涉及到这部分内容，没有办法同知识体系归类；

路程速度，火车过桥，鸡兔同笼等问题这部分是小奥里面的内容，没有必要放初中知识点中。

**Comment by mathedu4all** [comment]
旧知识点是系统已有的标签，通过与新知识点对应，从而实现新旧标签的转换.

如果旧标签没有新标签与其对应的新标签即会被弃用.

换元法、反证法作为常用数学方法，目前收录在应用数学与数学文化->常用数学方法，可以直接对应.

> 换元法，反证法，这部分问题针对性不强，很多知识点都有涉及到这部分内容，没有办法同知识体系归类；

这里知识点说白了就是标签，并不是严格意义上的知识点. 一道题可以有多个标签.

**Comment by mathedu4all** [comment]
如果旧标签没有新标签与其对应的新标签即会被弃用.
