### ISSUE TITLE
删除知识点

### ISSUE THREAD

**Issue by dangming25** [mathedu4all/mathcrowd-community#47]
旧知识点：
路程速度时间；平均速度；相遇问题基本知识；追及问题基本知识；火车过桥基本知识；盈亏问题基本知识；植树问题基本知识；和差问题基本知识；平均数问题基本知识；长方形；金字塔和沙漏模型；流水行船基本知识；等积变形；一半模型；燕尾模型；蝴蝶模型；鸟头模型；等量代换；毕克定理；发车间隔基本知识；鸡兔同笼问题基本知识；差倍问题基本知识；斐波那契数列基本知识；水中浸物问题基本知识；钟表行程基本知识；猎狗追兔基本知识；接送问题基本知识；经济问题基本知识；年龄问题基本知识；和倍问题基本知识；还原问题基本知识点；归一归总问题基本知识；连续自然数的立方和公式；山顶数公式；塔数公式；方阵问题基本知识；页码问题基本知识；牛吃草问题基本知识；工程问题基本知识；浓度问题基本知识；数表相关知识；

这些知识点都是小奥体系知识点，初中涉及到也不会是成体系设计，部分会出现在应用题里面，但是没必要去分，分类也比较模糊。

另外之后要做小奥体系的话，那么这部分内容肯定在里面的，还需要重新调整，现在做等于做了零。

**Comment by mathedu4all** [comment]
那这些知识点就不用写对应新知识点了～
