### ISSUE TITLE
在 Github 的 Markdown 里显示公式的方法

### ISSUE THREAD

**Issue by asukaminato0721** [mathedu4all/mathcrowd-community#49]
比如

https://github.com/mathedu4all/mathcrowd-community/wiki/%E9%9D%A2%E5%90%91%E6%9C%AA%E6%9D%A5%E7%9A%84%E7%9F%A5%E8%AF%86%E7%82%B9%E9%87%8D%E6%9E%84

里的

> 比如学习 "和函数" 时研究了 "$f (x)=x+\frac {1}{x}$ 函数"，

可以参考这里的方法

https://zhuanlan.zhihu.com/p/149281857

**Comment by mathedu4all** [comment]
有趣～
