### ISSUE TITLE
确定叶知识点（函数与分析）

### ISSUE THREAD

**Issue by mathedu4all** [mathedu4all/mathcrowd-community#5]
* 函数与分析
  * 函数基础
    * 函数的概念(对应说)
    * 函数的概念(变量说)
    * 函数的运算
      * 和（差）函数、积（商）函数
      * 函数的复合
    * 函数的图像
      * 函数图像的绘制
      * 轴对称函数图像的性质与判定
      * 中心对称函数图像的性质与判定 
    * 函数的奇偶性
    * 函数的单调性
    * 函数的周期性
    * 函数的值域、最值
    * 函数零点及零点定理
    * 反函数的概念及性质
  * 初等函数
    * 三角函数
      * 三角函数的定义(任意角)
      * 正余弦函数的性质与图像
      * 正切函数的性质与图像
      * y=Asin(wx+\phy)+k函数的性质与图像
    * 反三角函数
    * 指数函数的图像与性质
    * 对数函数的图像与性质
    * 幂函数的图像与性质
    * 特殊的初等函数
      * 正比例函数的图像与性质
      * 反比例函数的图像与性质
      * 一次函数的图像与性质
      * 二次函数
        * 二次函数的概念
          * 二次函数$y=ax^2$的图像和性质
          * 二次函数$y=a(x-h)^2+k$的图像和性质
          * 二次函数$y=ax^2+bx+c$的图像和性质 
      * 函数$f(x)=ax+\frac{b}{x}$的性质与图像
      * 函数$f(x)=\frac{ax+b}{cx+d}$的性质与图像
  * 其他特殊函数
    * 分段函数
    * 取整函数
    * 抽象函数

**Comment by mathedu4all** [comment]
高中知识点征求修改建议，待补充初中知识点

**Comment by ghost** [comment]
**抽象函数**也应该加进来，应该加到其他特殊函数吧

**Comment by ghost** [comment]
**反函数**现在考纲删掉了，是否有必要添加进来呢？

**Comment by mathedu4all** [comment]
> **反函数**现在考纲删掉了，是否有必要添加进来呢？

这是知识点树，另外还有教材章节树.
