### ISSUE TITLE
确定叶知识点（方程与代数）

### ISSUE THREAD

**Issue by mathedu4all** [mathedu4all/mathcrowd-community#6]
* 方程与代数
  * 代数式
    * 整式
      * 整式的概念
        * 字母表述数
        * 代数式
        * 代数式的值
        * 整式
      * 整式的加减
        * 合并同类项
        * 整式的加减
      * 整式的乘法
        * 同底数幂的乘法
        * 幂的乘方
        * 积的乘方
        * 整式的乘法
      * 乘法公式
        * 平方差公式
        * 完全平方公式
      * 因式分解
        * 提取公因式
        * 公式法
        * 十字相乘
        * 分组分解
      * 整式的除法
        * 同底数幂的除法
        * 单项式除以单项式
        * 多项式除以单项式
        * 多项式除以多项式
    * 分式
      * 分式
        * 分式的意义
        * 分式的基本性质
      * 分式的运算
        * 分式的乘除
        * 分式的加减
        * 整数指数幂及其运算
  * 集合与逻辑
    * 集合
      * 集合的概念及其表示方法
      * 集合与元素的关系
      * 集合之间的关系
        * 集合的相等
        * 集合的包含关系
      * 集合的运算
      * 命题
        * 命题、公理、定理的概念
      	* 逆命题和逆定理
        * 命题的四种形式及等价关系
        * 充分条件、必要条件
        * 命题的逻辑运算
        * 命题的推出关系
  * 数列
    * 数列的概念
    * 等差数列
    * 等比数列
    * 递推数列
    * 数列极限
      * 数列极限的概念及运算
      * 无穷等比数列的和
    * 数列求通项
      * 累乘法
      * 累加法
    * 数列求和
      * 裂项法
      * 错位相减
      * 逆序相加
  * 方程(组)
    * 方程与方程的解
        * 列方程
        * 方程的解
    * 一元整式方程 
      * 一元一次方程及其解法
      * 一元二次方程
        * 一元二次方程的定义
        * 一元二次方程的解法
          * 直接开方法
          * 配方法
          * 公式法
          * 因式分解法
        * 一元二次方程的根的判别式
        * 一元二次方程的根与系数的关系
        * 实系数一元二次方程
      * 其他一元整式方程
      * 二项方程
    * 一次方程组
      * 二元一次方程组及其解法
      * 三元一次方程组及其解法
    * 二次方程组
      * 二元二次方程和方程组
      * 二元二次方程组的解法
    * 分式方程
    * 无理方程
    * 指对数方程
    * 三角方程
  * 不等式
    * 不等式的简单性质(加法、乘法性质)
    * 不等式的基本性质
    * 基本(均值)不等式及其应用
    * 不等式的证明
      * 解不等式
        * 一次不等式
            * 一元一次不等式的解法
            * 一元一次不等式组的解法
        * 一元二次不等式
        * 分式不等式
        * 无理不等式
        * 绝对值不等式
        * 指对数不等式
        * 三角不等式
  * 三角恒等式
    * 诱导公式
    * 同角三角比的关系
    * 二倍角公式
    * 半角公式
    * 两角和(差)公式
    * 积化和差、和差化积公式 
  * 线性代数
    * 矩阵的概念
    * 矩阵的运算
    * 二、三阶行列式的展开
    * 克莱默法则
  * 数论
    * 整数与整除
      * 整数与整除的意义
      * 因数和倍数
      * 能被2，5整除的数
    * 分解素因数
      * 素数、合数与分解素因数
      * 公因数与最大公因数
      * 公倍数与最小公倍数

**Comment by mathedu4all** [comment]
高中知识点征求修改建议，待补充初中知识点

**Comment by dangming25** [comment]
初中知识点

**Comment by dangming25** [comment]
确定方程与代数版块三级及以下知识点:
方程与代数 
代数式
集合与逻辑 
集合 
集合的概念及其表示方法
集合与元素的关系
集合之间的关系 
集合的相等
集合的包含关系
集合的运算
命题 
命题的四种形式及等价关系
充分条件、必要条件
命题的逻辑运算
命题的推出关系
数列 
数列的概念
等差数列
等比数列
递推数列
数列极限 
数列极限的概念及运算
无穷等比数列的和
数列求通项 
累乘法
累加法
数列求和 
裂项法
错位相减
逆序相加
方程(组) 
实系数一元二次方程
指对数方程
三角方程
不等式 
不等式的基本性质
基本(均值)不等式及其应用
不等式的证明
解不等式 
一元二次不等式
分式不等式
无理不等式
绝对值不等式
指对数不等式
三角不等式
三角恒等式 
诱导公式
同角三角比的关系
二倍角公式
半角公式
两角和(差)公式
积化和差、和差化积公式
线性代数 
矩阵的概念
矩阵的运算
二、三阶行列式的展开
克莱默法则
数论

**Comment by mathcrowd-test** [comment]
啊啊

**Comment by dangming25** [comment]
* 方程与代数
  * 代数式
    * 整式
      * 整式的概念
        * 字母表述数
        * 代数式
        * 代数式的值
        * 整式
      * 整式的加减
        * 合并同类项
        * 整式的加减
      * 整式的乘法
        * 同底数幂的乘法
        * 幂的乘方
        * 积的乘方
        * 整式的乘法
      * 乘法公式
        * 平方差公式
        * 完全平方公式
      * 因式分解
        * 提取公因式
        * 公式法
        * 十字相乘
        * 分组分解
      * 整式的除法
        * 同底数幂的除法
        * 单项式除以单项式
        * 多项式除以单项式
        * 多项式除以多项式
    * 分式
      * 分式
        * 分式的意义
        * 分式的基本性质
      * 分式的运算
        * 分式的乘除
        * 分式的加减
        * 可以化为一元二次方程的分式方程
        * 整数指数幂及其运算
  * 集合与逻辑
    * 集合
      * 集合的概念及其表示方法
      * 集合与元素的关系
      * 集合之间的关系
        * 集合的相等
        * 集合的包含关系
      * 集合的运算
    * 命题
      * 命题的四种形式及等价关系
      * 充分条件、必要条件
      * 命题的逻辑运算
      * 命题的推出关系
  * 数列
    * 数列的概念
    * 等差数列
    * 等比数列
    * 递推数列
    * 数列极限
      * 数列极限的概念及运算
      * 无穷等比数列的和
    * 数列求通项
      * 累乘法
      * 累加法
    * 数列求和
      * 裂项法
      * 错位相减
      * 逆序相加
  * 方程(组)
    * 实系数一元二次方程
    * 指对数方程
    * 三角方程
  * 不等式
    * 不等式的基本性质
    * 基本(均值)不等式及其应用
    * 不等式的证明
    * 解不等式
      * 一元二次不等式
      * 分式不等式
      * 无理不等式
      * 绝对值不等式
      * 指对数不等式
      * 三角不等式
  * 三角恒等式
    * 诱导公式
    * 同角三角比的关系
    * 二倍角公式
    * 半角公式
    * 两角和(差)公式
    * 积化和差、和差化积公式 
  * 线性代数
    * 矩阵的概念
    * 矩阵的运算
    * 二、三阶行列式的展开
    * 克莱默法则
  * 数论

**Comment by dangming25** [comment]
* 方程与代数
  * 代数式
    * 整式
      * 整式的概念
        * 字母表述数
        * 代数式
        * 代数式的值
        * 整式
      * 整式的加减
        * 合并同类项
        * 整式的加减
      * 整式的乘法
        * 同底数幂的乘法
        * 幂的乘方
        * 积的乘方
        * 整式的乘法
      * 乘法公式
        * 平方差公式
        * 完全平方公式
      * 因式分解
        * 提取公因式
        * 公式法
        * 十字相乘
        * 分组分解
      * 整式的除法
        * 同底数幂的除法
        * 单项式除以单项式
        * 多项式除以单项式
        * 多项式除以多项式
    * 分式
      * 分式
        * 分式的意义
        * 分式的基本性质
      * 分式的运算
        * 分式的乘除
        * 分式的加减
        * 整数指数幂及其运算
  * 集合与逻辑
    * 集合
      * 集合的概念及其表示方法
      * 集合与元素的关系
      * 集合之间的关系
        * 集合的相等
        * 集合的包含关系
      * 集合的运算
* 命题
      * 命题和证明
        * 演绎证明
        * 命题、公理、定理
        * 逆命题和逆定理
      * 命题的四种形式及等价关系
      * 充分条件、必要条件
      * 命题的逻辑运算
      * 命题的推出关系
  * 数列
    * 数列的概念
    * 等差数列
    * 等比数列
    * 递推数列
    * 数列极限
      * 数列极限的概念及运算
      * 无穷等比数列的和
    * 数列求通项
      * 累乘法
      * 累加法
    * 数列求和
      * 裂项法
      * 错位相减
      * 逆序相加
  * 方程(组)
    * 一元一次方程
      * 方程与方程的解
        * 列方程
        * 方程的解
      * 一元一次方程及其解法
        * 一元一次方程的定义
        * 解一元一次方程
        * 一元一次方程的应用
    * 一次方程组
      * 二元一次方程组及其解法
        * 二元一次方程组的定义
        * 二元一次方程组的解法
      * 三元一次方程组及其解法
        * 三元一次方程组的定义
        * 三元一次方程组的解法
      * 一次方程组的应用
    * 一元二次方程
      * 一元二次方程
      * 一元二次方程的解法
      * 一元二次方程的根的判别式
      * 一元二次方程的根与系数的关系
      * 一元二次方程的应用
    * 二次方程组
      * 二元二次方程和方程组
      * 二元二次方程组的解法
      * 二元二次方程组的应用
    * 代数方程
      * 整式方程
        * 一元整式方程
        * 特殊的高次方程的解法
      * 分式方程
        * 可化为一元一次方程的方式方程
        * 可化为一元二次方程的分式方程
      * 无理方程
        * 可化为一元二次方程的无理方程
    * 实系数一元二次方程
    * 指对数方程
    * 三角方程
  * 不等式
    * 不等式的基本性质
    * 基本(均值)不等式及其应用
    * 不等式的证明
* 解不等式
      * 一次不等式
        * 不等式及其性质
        * 一元一次不等式的解法
        * 一元一次不等式的应用
        * 一元一次不等式的解法
        * 一元一次不等式组的应用
      * 一元二次不等式
      * 分式不等式
      * 无理不等式
      * 绝对值不等式
      * 指对数不等式
      * 三角不等式
  * 三角恒等式
    * 诱导公式
    * 同角三角比的关系
    * 二倍角公式
    * 半角公式
    * 两角和(差)公式
    * 积化和差、和差化积公式 
  * 线性代数
    * 矩阵的概念
    * 矩阵的运算
    * 二、三阶行列式的展开
    * 克莱默法则
  * 数论
    * 整数与整除
      * 整数与整除的意义
      * 因数和倍数
      * 能被2，5整除的数
    * 分解素因数
      * 素数、合数与分解素因数
      * 公因数与最大公因数
      * 公倍数与最小公倍数

**Comment by dangming25** [comment]
* 方程与代数
  * 代数式
    * 整式
      * 整式的概念
        * 字母表述数
        * 代数式
        * 代数式的值
        * 整式
      * 整式的加减
        * 合并同类项
        * 整式的加减
      * 整式的乘法
        * 同底数幂的乘法
        * 幂的乘方
        * 积的乘方
        * 整式的乘法
      * 乘法公式
        * 平方差公式
        * 完全平方公式
      * 因式分解
        * 提取公因式
        * 公式法
        * 十字相乘
        * 分组分解
      * 整式的除法
        * 同底数幂的除法
        * 单项式除以单项式
        * 多项式除以单项式
        * 多项式除以多项式
    * 分式
      * 分式
        * 分式的意义
        * 分式的基本性质
      * 分式的运算
        * 分式的乘除
        * 分式的加减
        * 整数指数幂及其运算
  * 集合与逻辑
    * 集合
      * 集合的概念及其表示方法
      * 集合与元素的关系
      * 集合之间的关系
        * 集合的相等
        * 集合的包含关系
      * 集合的运算
      * 命题
        * 命题和证明
        * 演绎证明
        * 命题、公理、定理
        * 逆命题和逆定理
        * 命题的四种形式及等价关系
        * 充分条件、必要条件
        * 命题的逻辑运算
        * 命题的推出关系
  * 数列
    * 数列的概念
    * 等差数列
    * 等比数列
    * 递推数列
    * 数列极限
      * 数列极限的概念及运算
      * 无穷等比数列的和
    * 数列求通项
      * 累乘法
      * 累加法
    * 数列求和
      * 裂项法
      * 错位相减
      * 逆序相加
  * 方程(组)
    * 一元一次方程
      * 方程与方程的解
        * 列方程
        * 方程的解
      * 一元一次方程及其解法
        * 一元一次方程的定义
        * 解一元一次方程
        * 一元一次方程的应用
    * 一次方程组
      * 二元一次方程组及其解法
        * 二元一次方程组的定义
        * 二元一次方程组的解法
      * 三元一次方程组及其解法
        * 三元一次方程组的定义
        * 三元一次方程组的解法
      * 一次方程组的应用
    * 一元二次方程
      * 一元二次方程
      * 一元二次方程的解法
      * 一元二次方程的根的判别式
      * 一元二次方程的根与系数的关系
      * 一元二次方程的应用
    * 二次方程组
      * 二元二次方程和方程组
      * 二元二次方程组的解法
      * 二元二次方程组的应用
    * 代数方程
      * 整式方程
        * 一元整式方程
        * 特殊的高次方程的解法
      * 分式方程
        * 可化为一元一次方程的方式方程
        * 可化为一元二次方程的分式方程
      * 无理方程
        * 可化为一元二次方程的无理方程
    * 实系数一元二次方程
    * 指对数方程
    * 三角方程
  * 不等式
    * 不等式的基本性质
    * 基本(均值)不等式及其应用
* 不等式的证明
  * 解不等式
      * 一次不等式
        * 不等式及其性质
        * 一元一次不等式的解法
        * 一元一次不等式的应用
        * 一元一次不等式的解法
        * 一元一次不等式组的应用
      * 一元二次不等式
      * 分式不等式
      * 无理不等式
      * 绝对值不等式
      * 指对数不等式
      * 三角不等式
  * 三角恒等式
    * 诱导公式
    * 同角三角比的关系
    * 二倍角公式
    * 半角公式
    * 两角和(差)公式
    * 积化和差、和差化积公式 
  * 线性代数
    * 矩阵的概念
    * 矩阵的运算
    * 二、三阶行列式的展开
    * 克莱默法则
  * 数论
    * 整数与整除
      * 整数与整除的意义
      * 因数和倍数
      * 能被2，5整除的数
    * 分解素因数
      * 素数、合数与分解素因数
      * 公因数与最大公因数
      * 公倍数与最小公倍数

**Comment by dangming25** [comment]
* 方程与代数
  * 代数式
    * 整式
      * 整式的概念
        * 字母表述数
        * 代数式
        * 代数式的值
        * 整式
      * 整式的加减
        * 合并同类项
        * 整式的加减
      * 整式的乘法
        * 同底数幂的乘法
        * 幂的乘方
        * 积的乘方
        * 整式的乘法
      * 乘法公式
        * 平方差公式
        * 完全平方公式
      * 因式分解
        * 提取公因式
        * 公式法
        * 十字相乘
        * 分组分解
      * 整式的除法
        * 同底数幂的除法
        * 单项式除以单项式
        * 多项式除以单项式
        * 多项式除以多项式
    * 分式
      * 分式
        * 分式的意义
        * 分式的基本性质
      * 分式的运算
        * 分式的乘除
        * 分式的加减
        * 整数指数幂及其运算
  * 集合与逻辑
    * 集合
      * 集合的概念及其表示方法
      * 集合与元素的关系
      * 集合之间的关系
        * 集合的相等
        * 集合的包含关系
      * 集合的运算
      * 命题
        * 命题和证明
        * 演绎证明
        * 命题、公理、定理
        * 逆命题和逆定理
        * 命题的四种形式及等价关系
        * 充分条件、必要条件
        * 命题的逻辑运算
        * 命题的推出关系
  * 数列
    * 数列的概念
    * 等差数列
    * 等比数列
    * 递推数列
    * 数列极限
      * 数列极限的概念及运算
      * 无穷等比数列的和
    * 数列求通项
      * 累乘法
      * 累加法
    * 数列求和
      * 裂项法
      * 错位相减
      * 逆序相加
  * 方程(组)
    * 一元一次方程
      * 方程与方程的解
        * 列方程
        * 方程的解
      * 一元一次方程及其解法
        * 一元一次方程的定义
        * 解一元一次方程
        * 一元一次方程的应用
    * 一次方程组
      * 二元一次方程组及其解法
        * 二元一次方程组的定义
        * 二元一次方程组的解法
      * 三元一次方程组及其解法
        * 三元一次方程组的定义
        * 三元一次方程组的解法
      * 一次方程组的应用
    * 一元二次方程
      * 一元二次方程
        * 一元二次方程的定义
      * 一元二次方程的解法
        * 直接开方法
        * 配方法
        * 公式法
        * 因式分解法
      * 一元二次方程的根的判别式
      * 一元二次方程的根与系数的关系
      * 一元二次方程的应用
    * 二次方程组
      * 二元二次方程和方程组
      * 二元二次方程组的解法
      * 二元二次方程组的应用
    * 代数方程
      * 整式方程
        * 一元整式方程
        * 二项方程
      * 分式方程
        * 可化为一元二次方程的分式方程
      * 无理方程
        * 可化为一元二次方程的无理方程
    * 实系数一元二次方程
    * 指对数方程
    * 三角方程
  * 不等式
    * 不等式的基本性质
    * 基本(均值)不等式及其应用
* 不等式的证明
  * 解不等式
      * 一次不等式
        * 不等式及其性质
        * 一元一次不等式的解法
        * 一元一次不等式的应用
        * 一元一次不等式的解法
        * 一元一次不等式组的应用
      * 一元二次不等式
      * 分式不等式
      * 无理不等式
      * 绝对值不等式
      * 指对数不等式
      * 三角不等式
  * 三角恒等式
    * 诱导公式
    * 同角三角比的关系
    * 二倍角公式
    * 半角公式
    * 两角和(差)公式
    * 积化和差、和差化积公式 
  * 线性代数
    * 矩阵的概念
    * 矩阵的运算
    * 二、三阶行列式的展开
    * 克莱默法则
  * 数论
    * 整数与整除
      * 整数与整除的意义
      * 因数和倍数
      * 能被2，5整除的数
    * 分解素因数
      * 素数、合数与分解素因数
      * 公因数与最大公因数
      * 公倍数与最小公倍数

**Comment by dangming25** [comment]
这是添加进去初中的内容框架，大家可以讨论一下

**Comment by dangming25** [comment]
* 方程与代数
  * 代数式
    * 整式
      * 整式的概念
        * 字母表述数
        * 代数式
        * 代数式的值
        * 整式
      * 整式的加减
        * 合并同类项
        * 整式的加减
      * 整式的乘法
        * 同底数幂的乘法
        * 幂的乘方
        * 积的乘方
        * 整式的乘法
      * 乘法公式
        * 平方差公式
        * 完全平方公式
      * 因式分解
        * 提取公因式
        * 公式法
        * 十字相乘
        * 分组分解
      * 整式的除法
        * 同底数幂的除法
        * 单项式除以单项式
        * 多项式除以单项式
        * 多项式除以多项式
    * 分式
      * 分式
        * 分式的意义
        * 分式的基本性质
      * 分式的运算
        * 分式的乘除
        * 分式的加减
        * 整数指数幂及其运算
  * 集合与逻辑
    * 集合
      * 集合的概念及其表示方法
      * 集合与元素的关系
      * 集合之间的关系
        * 集合的相等
        * 集合的包含关系
      * 集合的运算
      * 命题
        * 命题和证明
          * 命题、公理、定理
          * 逆命题和逆定理
        * 命题的四种形式及等价关系
        * 充分条件、必要条件
        * 命题的逻辑运算
        * 命题的推出关系
  * 数列
    * 数列的概念
    * 等差数列
    * 等比数列
    * 递推数列
    * 数列极限
      * 数列极限的概念及运算
      * 无穷等比数列的和
    * 数列求通项
      * 累乘法
      * 累加法
    * 数列求和
      * 裂项法
      * 错位相减
      * 逆序相加
  * 方程(组)
    * 一元一次方程
      * 方程与方程的解
        * 列方程
        * 方程的解
      * 一元一次方程及其解法
        * 一元一次方程的定义
        * 解一元一次方程
        * 一元一次方程的应用
    * 一次方程组
      * 二元一次方程组及其解法
        * 二元一次方程组的定义
        * 二元一次方程组的解法
      * 三元一次方程组及其解法
        * 三元一次方程组的定义
        * 三元一次方程组的解法
      * 一次方程组的应用
    * 一元二次方程
      * 一元二次方程
        * 一元二次方程的定义
      * 一元二次方程的解法
        * 直接开方法
        * 配方法
        * 公式法
        * 因式分解法
      * 一元二次方程的根的判别式
      * 一元二次方程的根与系数的关系
      * 一元二次方程的应用
    * 二次方程组
      * 二元二次方程和方程组
      * 二元二次方程组的解法
      * 二元二次方程组的应用
    * 代数方程
      * 整式方程
        * 一元整式方程
        * 二项方程
      * 分式方程
        * 可化为一元二次方程的分式方程
      * 无理方程
        * 可化为一元二次方程的无理方程
    * 实系数一元二次方程
    * 指对数方程
    * 三角方程
  * 不等式
    * 不等式的基本性质
    * 基本(均值)不等式及其应用
* 不等式的证明
  * 解不等式
      * 一次不等式
        * 不等式及其性质
        * 一元一次不等式的解法
        * 一元一次不等式的应用
        * 一元一次不等式的解法
        * 一元一次不等式组的应用
      * 一元二次不等式
      * 分式不等式
      * 无理不等式
      * 绝对值不等式
      * 指对数不等式
      * 三角不等式
  * 三角恒等式
    * 诱导公式
    * 同角三角比的关系
    * 二倍角公式
    * 半角公式
    * 两角和(差)公式
    * 积化和差、和差化积公式 
  * 线性代数
    * 矩阵的概念
    * 矩阵的运算
    * 二、三阶行列式的展开
    * 克莱默法则
  * 数论
    * 整数与整除
      * 整数与整除的意义
      * 因数和倍数
      * 能被2，5整除的数
    * 分解素因数
      * 素数、合数与分解素因数
      * 公因数与最大公因数
      * 公倍数与最小公倍数

**Comment by mathedu4all** [comment]
初中不等式的性质有几条性质？

**Comment by mathedu4all** [comment]
> * 同底数幂的乘法
> * 幂的乘方
> * 积的乘方

是否与“数与运算板块”重复？

**Comment by mathedu4all** [comment]
> 整式的加减
> 合并同类项

是否有必要将合并同类项与整式加减区分？ 因为放在不同课时吗？

**Comment by mathedu4all** [comment]
> 方程与方程的解
> 
> * 列方程
> * 方程的解

这个不应该放在一元一次方程下级吧～

**Comment by mathedu4all** [comment]
> 一元二次方程的解法
> 
> * 直接开方法
> * 配方法
> * 公式法
> * 因式分解法

是否有必要区分不同解法？

**Comment by mathedu4all** [comment]
> * 二元二次方程和方程组
> * 二元二次方程组的解法
> * 二元二次方程组的应用

所有都方程设置了 定义、解法及应用是否有必要.

 合并为“二元二次方程和方程组及其解法”?

若试题是应用题则在这个标签基础上，再添加一个数学应用题标签即可.

这样就不需要设置这么多 ××××的应用 的标签了.

**Comment by dangming25** [comment]
> 初中不等式的性质有几条性质？

初中不等式的性质这部分内容分为
1.不等式的两边都加上或减去同一个数或同一个整式，不等号方向不变；
2.不等式同乘正和负

**Comment by dangming25** [comment]
> 整式的加减
> 合并同类项
> 
> 是否有必要将合并同类项与整式加减区分？ 因为放在不同课时吗？

这个是放在不同课时的，合并同类项是主要是同类项的定义，整式加减更多的是运算，所以会区别开来

**Comment by mathedu4all** [comment]
已提交
