### ISSUE TITLE
确定叶知识点（应用数学与数学文化）

### ISSUE THREAD

**Issue by mathedu4all** [mathedu4all/mathcrowd-community#7]
* 应用数学与数学文化
  * 算法
    * 算法的概念
    * 常用算法
      * 秦九韶算法
      * 辗转相除法(欧几里得算法)
      * 二分法
      * 牛顿切线法
      * 进位制转换
    * 算法框图
    * 计算器的使用
  * 组合计数
    * 加法原理(分类)
    * 乘法原理(分步)
    * 排列数公式及性质
    * 组合数公式及性质
    * 排列组合问题
    * 常见排列组合模型
      * 球盒模型
      * 染色模型
      * 指派模型
    * 容斥原理
    * 抽屉原理 
    * 二项式定理
  * 概率与统计
    * 概率
      * 随机事件
        * 随机事件的基本概念
        * 随机事件间的关系
          * 互斥事件、对立事件
          * 相互独立的事件
        * 随机事件间的运算
          * 事件和(并)
          * 事件积(交)
      * 概率的定义
        * 统计定义(频率)
        * 古典概型
        * 几何概型
        * 公理化定义
      * 条件概率
      * 概率的性质
        * 概率加法公式
        * 概率乘法公式
        * 全概率公式
        * 贝叶斯公式
      * 随机变量
        * 随机变量的定义
        * 随机变量的特征
          * 离散型随机变量的期望
          * 连续性随机变量的期望
          * 离散型随机变量的分布列
          * 连续型随机变量的密度函数
          * 连续型随机变量的分布函数
        * 常见随机变量的分布
          * 独立重复试验与二项分布
          * 正态分布及其曲线
          * 泊松分布
          * 超几何分布
      * 用频率估计概率
    * 统计
      * 描述性统计量
        * 平均数
        * 加权平均数
        * 分位数
        * 中位数、众数
        * 方差、标准差、极差
        * 统计量的选择
        * 协方差
        * 相关系数
      * 抽样调查
        * 抽样调查的相关概念
        * 抽样调查的过程与方法
          * 简单随机抽样法
          * 系统抽样法
          * 分层抽样法
        *  用样本估计总体
      * 频数与频率
        * 频数与频率的概念
        * 频数（率）分布表
        * 频数（率）分布直方图
        * 频数（率）分布折线图
      * 统计图表
        * 折线图
        * 柱状图
        * 扇形图
        * 茎叶图
        * 散点图
        * 其他统计图
        * 统计图的选择
      * 统计推断
        * 回归分析
          * 线性回归方程
          * 最小二乘法
        * 假设检验
          * 独立性检验
  * 最优化问题
    * 线性规划
    * 非线性规划
  * 数学应用题
  * 数学史
    * 数系扩张
  * 数学思想方法
    * 归纳-猜想-证明
  * 常用数学方法
    * 枚举法
    * 极端法

**Comment by sunpingana** [comment]
* 应用数学与数学建模 
  * 算法
  * 组合计数

**Comment by sunpingana** [comment]
> 确定应用数学与数学建模版块三级及以下知识点:
> 
> * 应用数学与数学建模
>   
>   * 算法

>   * 组合计数
>   * 概率与统计
>   * 最优化问题
>   * 数学应用题

**Comment by sunpingana** [comment]
确定应用数学与数学建模版块三级及以下知识点:

应用数学与数学建模
算法
  * 小算法
组合计数
概率与统计
最优化问题
数学应用题

**Comment by 52511338** [comment]
先标记一下，明天开始整理。

**Comment by mathedu4all** [comment]
> > 确定应用数学与数学建模版块三级及以下知识点:
> > 
> > * 应用数学与数学建模
> >   
> >   * 算法
> >     
> >     * 排序问题
> >     * 算法的多样性
> >     * 流程图
> >     * 程序框图
> >     * 统筹图
> >     * 结构图
> >     * 秦九韶算法
> >     * 进位制
> >   * 组合计数
> >     
> >     * 分类加法计数原理
> >     * 分步乘法计数原理
> >     * 排列及排列数公式
> >     * 组合及组合数公式
> >     * 排列组合的应用
> >     * 二项式定理
> >   * 概率与统计
> >     
> >     * 概率
> >       
> >       * 随机事件
> >       * 概率及其性质
> >       * 互斥事件与对立事件
> >       * 互斥事件的概率加法公式
> >       * 等可能事件及其概率
> >       * 相互独立事件及其概率
> >       * n次独立重复实验的概率
> >       * 古典概型
> >       * 列举法计算基本事件总数
> >       * 随机数与随机数表
> >       * 模拟方法估计概率
> >       * 几何概型
> >       * 离散型随机变量及其分布列
> >       * 离散型随机变量的期望
> >       * 超几何分布
> >       * 条件概率
> >       * 二项分布
> >       * 连续型随机变量
> >       * 正态分布及其曲线
> >       * 概率的应用
> >     * 统计与统计案例
> >       
> >       * 简单的随机抽样
> >       * 分层抽样方法
> >       * 系统抽样方法
> >       * 收集数据的方法
> >       * 分布和频率分布表
> >       * 频率分布直方图
> >       * 频率分布折线图
> >       * 密度曲线
> >       * 茎叶图
> >       * 众数、中位数与平均数
> >       * 极差、方差与标准差
> >       * 用样本估计整体
> >       * 变量间的相关关系
> >       * 散点图
> >       * 最小二乘法
> >       * 线性回归方程
> >       * 独立性检验
> >       * 回归分析
> >       * 相关系数
> >       * 实际推断原理和假设检验
> >   * 最优化问题
> >     
> >     * 线性规划
> >   * 数学应用题
> 
> 我这边暂时就能写这么多，最后两个二级知识点**最优化问题**、**数学应用题**这两个板块我不太熟悉所以没完成，看看别的老师能不能补充一下。至于前面的部分，希望大家提出宝贵的修改意见。

感觉概率和统计下面可以在设置些四级知识点、如“常用随机变量及其概率分布”等.

**Comment by sunpingana** [comment]
> 确定应用数学与数学建模版块三级及以下知识点:
> 
> * 应用数学与数学建模
>   
>   * 算法
>   * 组合计数
>   * 概率与统计
       * 百分比
         * 等可能事件  
       *统计初步
         *  统计的意义 
           * 数据整理与表示 
       * 统计的意义   
        *基本的统计量
>   * 最优化问题
>   * 数学应用题

**Comment by sunpingana** [comment]
* 应用数学与数学建模
  * 算法
  * 组合计数
  * 概率与统计
    * 百分比
      * 等可能事件
    * 统计初步
      * 统计的意义
        * 数据的整理与表示
        * 统计的意义
      *  基本统计量
        * 表示一组数据平均水平的量
        * 表示一组数据波动程度的量
        * 表示一组数据分布的量
        * 统计实习

**Comment by ghost** [comment]
> > > 确定应用数学与数学建模版块三级及以下知识点:
> > > 
> > > * 应用数学与数学建模
> > >   
> > >   * 算法
> > >     
> > >     * 排序问题
> > >     * 算法的多样性
> > >     * 流程图
> > >     * 程序框图
> > >     * 统筹图
> > >     * 结构图
> > >     * 秦九韶算法
> > >     * 进位制
> > >   * 组合计数
> > >     
> > >     * 分类加法计数原理
> > >     * 分步乘法计数原理
> > >     * 排列及排列数公式
> > >     * 组合及组合数公式
> > >     * 排列组合的应用
> > >     * 二项式定理
> > >   * 概率与统计
> > >     
> > >     * 概率
> > >       
> > >       * 随机事件
> > >       * 概率及其性质
> > >       * 互斥事件与对立事件
> > >       * 互斥事件的概率加法公式
> > >       * 等可能事件及其概率
> > >       * 相互独立事件及其概率
> > >       * n次独立重复实验的概率
> > >       * 古典概型
> > >       * 列举法计算基本事件总数
> > >       * 随机数与随机数表
> > >       * 模拟方法估计概率
> > >       * 几何概型
> > >       * 离散型随机变量及其分布列
> > >       * 离散型随机变量的期望
> > >       * 超几何分布
> > >       * 条件概率
> > >       * 二项分布
> > >       * 连续型随机变量
> > >       * 正态分布及其曲线
> > >       * 概率的应用
> > >     * 统计与统计案例
> > >       
> > >       * 简单的随机抽样
> > >       * 分层抽样方法
> > >       * 系统抽样方法
> > >       * 收集数据的方法
> > >       * 分布和频率分布表
> > >       * 频率分布直方图
> > >       * 频率分布折线图
> > >       * 密度曲线
> > >       * 茎叶图
> > >       * 众数、中位数与平均数
> > >       * 极差、方差与标准差
> > >       * 用样本估计整体
> > >       * 变量间的相关关系
> > >       * 散点图
> > >       * 最小二乘法
> > >       * 线性回归方程
> > >       * 独立性检验
> > >       * 回归分析
> > >       * 相关系数
> > >       * 实际推断原理和假设检验
> > >   * 最优化问题
> > >     
> > >     * 线性规划
> > >   * 数学应用题
 
 我这边暂时就能写这么多，最后两个二级知识点**最优化问题**、**数学应用题**这两个板块我不太熟悉所以没完成，看看别的老师能不能补充一下。至于前面的部分，希望大家提出宝贵的修改意见。

**Comment by 52511338** [comment]
确定应用数学与数学建模版块三级及以下知识点:
    
    * 应用数学与数学建模
      
      * 算法
        
        * 排序问题
        * 算法的多样性
        * 流程图
        * 程序框图
        * 统筹图
        * 结构图
        * 秦九韶算法
        * 进位制
      * 组合计数
        
        * 分类加法计数原理
        * 分步乘法计数原理
        * 排列及排列数公式
        * 组合及组合数公式
        * 排列组合的应用
        * 二项式定理
      * 概率与统计
        
        * 概率
          
          * 随机事件
          * 概率及其性质
          * 互斥事件与对立事件
          * 互斥事件的概率加法公式
          * 等可能事件及其概率
          * 相互独立事件及其概率
          * n次独立重复实验的概率
          * 古典概型
          * 列举法计算基本事件总数
          * 随机数与随机数表
          * 模拟方法估计概率
          * 几何概型
          * 离散型随机变量及其分布列
          * 离散型随机变量的期望
          * 超几何分布
          * 条件概率
          * 二项分布
          * 连续型随机变量
          * 正态分布及其曲线
          * 概率的应用
        * 统计与统计案例
          
          * 简单的随机抽样
          * 分层抽样方法
          * 系统抽样方法
          * 收集数据的方法
          * 分布和频率分布表
          * 频率分布直方图
          * 频率分布折线图
          * 密度曲线
          * 茎叶图
          * 众数、中位数与平均数
          * 极差、方差与标准差
          * 用样本估计整体
          * 变量间的相关关系
          * 散点图
          * 最小二乘法
          * 线性回归方程
          * 独立性检验
          * 回归分析
          * 相关系数
          * 实际推断原理和假设检验
      * 最优化问题
        
        * 线性规划
      * 数学应用题
 
 我这边暂时就能写这么多，最后两个二级知识点**最优化问题**、**数学应用题**这两个板块我不太熟悉所以没完成，看看别的老师能不能补充一下。至于前面的部分，希望大家提出宝贵的修改意见。

我再看看能不能添加些四级知识点

**Comment by sunpingana** [comment]
* 应用数学与数学建模
  * 算法
  * 组合计数
  * 概率与统计
    * 统计初步
      * 统计的意义
        * 数据的整理与表示
        * 统计的意义
      *  基本统计量
        * 平均数
        * 方差
        * 众数与中位数
        * 统计实习

**Comment by ghost** [comment]
* 应用数学与数学建模
  
  * 算法
    
    * 排序问题
    * 算法的多样性
    * 流程图
    * 程序框图
    * 统筹图
    * 结构图
    * 秦九韶算法
    * 进位制
  * 组合计数
    
    * 分类加法计数原理
    * 分步乘法计数原理
    * 排列及排列数公式
    * 组合及组合数公式
    * 排列组合的应用
    * 二项式定理
  * 概率与统计
    
    * 概率
      
      * 随机事件
      * 概率及其性质
      * 互斥事件与对立事件
      * 互斥事件的概率加法公式
      * 等可能事件及其概率
      * 相互独立事件及其概率
      * n次独立重复实验的概率
      * 古典概型
      * 列举法计算基本事件总数
      * 随机数与随机数表
      * 模拟方法估计概率
      * 几何概型
      * 离散型随机变量及其分布列
      * 离散型随机变量的期望
      * 超几何分布
      * 条件概率
      * 二项分布
      * 连续型随机变量
      * 正态分布及其曲线
      * 概率的应用
    * 统计与统计案例
      
      * 简单的随机抽样
      * 分层抽样方法
      * 系统抽样方法
      * 收集数据的方法
      * 分布和频率分布表
      * 频率分布直方图
      * 频率分布折线图
      * 密度曲线
      * 茎叶图
      * 众数、中位数与平均数
      * 极差、方差与标准差
      * 用样本估计整体
      * 变量间的相关关系
      * 散点图
      * 最小二乘法
      * 线性回归方程
      * 独立性检验
      * 回归分析
      * 相关系数
      * 实际推断原理和假设检验
  * 最优化问题
    
    * 线性规划
  * 数学应用题

**Comment by sunpingana** [comment]
* 应用数学与数学建模
  * 算法
    * 定义新预算
    * 材料阅读分析
  * 组合计数
    * 排列与组合问题
    * 加法和乘法原理
    * 计数方法
    * 染色问题
    * 抽屉原理
    * 容斥原理
    * 枚举法
    * 极端处理
    * 对应计数
  * 概率与统计
    * 统计
      * 数据收集与处理
        * 抽样调查
          * 收集数据的过程与方法
          * 全面调查与抽样调查
          * 总体，个体，样本，样本容量
          * 抽样调查的可靠性
          * 用样本估计总体
        * 频数与频率
          * 频数与频率
          * 频数（率）分布表
          * 频数（率）分布直方图
          * 频数（率）分布折线图
        * 统计图和统计表
          * 统计表
          * 扇形统计图
          * 条形统计图
          * 折线统计图
          * 统计图的选择
          * 其他统计图
      * 数据分析
        * 平均数
          * 算数平均数
          * 加权平均数
          * 计算器—平均数
        * 中位数
        * 众数
        * 方差
        * 标准差
          * 计算器—标准差与方差
        * 极差
        * 统计量的选择
    * 概率
      * 随机事件
      * 可能性的大小
      * 概率的意义
      * 概率公式
      * 几何概率
      * 列表法与树状图法
      * 游戏公平性
      * 利用频率估计概率
      * 模拟实验
  * 最优化问题
    * 最值为题
      * 几何最值
      * 函数最值
      * 代数最值
      * 智巧趣题最值
    * 最优方案选择
      * 百分数应用问题最佳方案
      * 其它应用题最佳方案
  * 数学应用题
    * 整数问题有关应用题
      * 进制问题
      * 整除问题
      * 余数问题
      * 质数合数问题
      * 平方数问题
      * 其它数论应用题
    * 百分数应用题
      * 经济问题
      * 浓度问题
      * 其它百分数应用题
    * 行程问题
    * 函数有关应用题
      * 一次函数应用题
      * 二次函数应用题
    * 方程与不等式有关应用题
      * 一元一次方程应用题
      * 一元二次方程应用题
      * 二元一次方程（组）应用题
      * 一元二次方程应用题
      * 不定方程应用题
      * 分数方程应用题
      * 不等式（组）应用题
    * 几何有关应用题
    * 逻辑推理方面应用题
      * 抽屉原理
      * 排列与组合问题
      * 容斥原理
      * 极端原理
      * 枚举法
      * 其它计数问题
      * 智巧趣题有关应用

**Comment by sunpingana** [comment]
这是我写的初中数学这一块，大家讨论一下吧

**Comment by sunpingana** [comment]
* 应用数学与数学建模
  * 算法
    * 定义新预算
    * 材料阅读分析
  * 组合计数
    * 排列与组合问题
    * 加法和乘法原理
    * 计数方法
    * 染色问题
    * 抽屉原理
    * 容斥原理
    * 枚举法
    * 极端处理
    * 对应计数
  * 概率与统计
    * 统计
      * 数据收集与处理
        * 抽样调查
          * 收集数据的过程与方法
          * 全面调查与抽样调查
          * 总体，个体，样本，样本容量
          * 抽样调查的可靠性
          * 用样本估计总体
        * 频数与频率
          * 频数与频率
          * 频数（率）分布表
          * 频数（率）分布直方图
          * 频数（率）分布折线图
        * 统计图和统计表
          * 统计表
          * 扇形统计图
          * 条形统计图
          * 折线统计图
          * 统计图的选择
          * 其他统计图
      * 数据分析
        * 平均数
          * 算数平均数
          * 加权平均数
          * 计算器—平均数
        * 中位数
        * 众数
        * 方差
        * 标准差
          * 计算器—标准差与方差
        * 极差
        * 统计量的选择
    * 概率
      * 随机事件
      * 可能性的大小
      * 概率的意义
      * 概率公式
      * 几何概率
      * 列表法与树状图法
      * 游戏公平性
      * 利用频率估计概率
      * 模拟实验
  * 最优化问题
    * 最值为题
      * 几何最值
      * 函数最值
      * 代数最值
      * 智巧趣题最值
    * 最优方案选择
      * 百分数应用问题最佳方案
      * 其它应用题最佳方案
  * 数学应用题

**Comment by sunpingana** [comment]
* 应用数学与数学建模
  * 算法
    * 定义新预算
    * 材料阅读分析
  * 组合计数
    * 排列与组合问题
    * 加法和乘法原理
    * 计数方法
    * 染色问题
    * 抽屉原理
    * 容斥原理
    * 枚举法
    * 极端处理
    * 对应计数
  * 概率与统计
    * 统计
      * 数据收集与处理
        * 抽样调查
          * 收集数据的过程与方法
          * 全面调查与抽样调查
          * 总体，个体，样本，样本容量
          * 抽样调查的可靠性
          * 用样本估计总体
        * 频数与频率
          * 频数与频率
          * 频数（率）分布表
          * 频数（率）分布直方图
          * 频数（率）分布折线图
        * 统计图和统计表
          * 统计表
          * 扇形统计图
          * 条形统计图
          * 折线统计图
          * 统计图的选择
          * 其他统计图
      * 数据分析
        * 平均数
          * 算数平均数
          * 加权平均数
          * 计算器—平均数
        * 中位数
        * 众数
        * 方差
        * 标准差
          * 计算器—标准差与方差
        * 极差
        * 统计量的选择
    * 概率
      * 随机事件
      * 可能性的大小
      * 概率的意义
      * 概率公式
      * 几何概率
      * 列表法与树状图法
      * 游戏公平性
      * 利用频率估计概率
      * 模拟实验
  * 最优化问题
    * 最值问题
      * 几何最值
      * 函数最值
      * 代数最值
      * 智巧趣题最值
    * 最优方案选择
      * 百分数应用问题最佳方案
      * 其它应用题最佳方案
  * 数学应用题

**Comment by mathedu4all** [comment]
已提交
