### ISSUE TITLE
确定叶知识点（图形与几何）

### ISSUE THREAD

**Issue by mathedu4all** [mathedu4all/mathcrowd-community#8]
确定图形与几何版块三级及以下知识点:

* 图形与几何
  * 几何体
    * 空间几何体
      * 多面体(棱柱、棱锥)
      * 旋转体(圆柱、圆锥、球)
      * 空间几何体的截面
      * 空间几何体的体积、表面积
      * 球面距离
  * 解析几何
    * 曲线轨迹与方程
    * 椭圆方程及其性质
    * 双曲线方程及其性质
    * 圆的方程及其性质
    * 抛物线方程及其性质
    * 直线方程及其性质
    * 参数方程
    * 极坐标方程
    * 坐标系变换
  * 向量几何
    * 向量分解定理
    * 向量的运算与关系
      * 向量加减法
      * 向量数乘与平行
      * 向量的数量积与垂直
      * 向量的模
      * 向量的夹角
    * 向量的坐标表示及其坐标运算
  * 欧式几何
    * 平面几何
      * 平面几何量
        * 平面两直线的的夹角
        * 平面点到直线的距离
    * 立体几何
      * 平面的概念、性质及表示
      * 空间平面与平面的位置关系
        * 面面垂直的性质与判定
        * 面面平行的性质与判定
      *  空间直线与平面的位置关系
        * 线面平行的性质与判定
        * 线面垂直的性质与判定
      * 空间直线与直线的位置关系(异面直线)
      * 空间几何量
        * 二面角
        * 线面角
        * 异面直线所成的角
        * 异面直线间的距离
        * 空间点到平面(直线)的距离
      * 三视图、直观图、投影
  * 三角学
    * 正弦定理
    * 余弦定理
    * 三角形面积公式($S=\frac{1}{2}ab\sin C$)

**Comment by mathedu4all** [comment]
高中知识点征求修改建议，待补充初中知识点

**Comment by ghost** [comment]
三角学下面是不是该添加一个“三角形面积公式”

**Comment by mathedu4all** [comment]
> 三角学下面是不是该添加一个“三角形面积公式”

已添加，谢谢.

**Comment by dangming25** [comment]
* 图形与几何
  * 基本图形、几何体的概念及性质
    * 几何图形初步
      * 几何图形
        * 立体图形与平面图形
        * 点、线、面、体
      * 直线、射线、线段
      * 角
        * 角的定义及其表
        * 角的比较和运算
        * 余角与补角
    * 投影与视图
      * 投影
      * 三视图
    * 相交线与平行线
      * 相交线
        * 相交线的定义
        * 垂直
        * 同位角、内错角、同旁内角
      * 平行线
       * 平行线的定义
       * 平行线的判定
       * 平行线的性质
  * 几何量
    * 锐角的三角比
      * 锐角的三角比
        * 锐角三角比的意义
        * 求锐角的三角比
      * 解直角三角形
        * 解直角三角形
        * 解直角三角形的应用
  * 几何关系
    * 三角形
      * 三角形
        * 与三角形有关的线段
          * 三角形的边
          * 三角形的高、中线、角平分线
          * 三角形的稳定性
        * 与三角形有关的角
          * 三角形的内角
          * 三角形的外角
      * 全等三角形
        * 全等三角形的概念及其性质
        * 全等三角形的判定
          * SAS
          * ASA
          * AAS
          * SSS
          * HL
        * 角的平分线
          * 角平分线的性质
          * 角平分线的判定
      * 相似
        * 图形的相似
        * 相似三角形
          * 比例线段
          * 相似三角形的判定 
          * 相似三角形的性质
        * 位似
    * 勾股定理
      * 勾股定理
      * 勾股定理的逆定理
      * 两点的距离公式
    * 四边形
      * 多边形的内角和与外角和
        * 多边形的定义
        * 多边形的内角和
        * 多边形的外角和
      * 平行四边性
        * 平行四边形
          * 平行四边形的性质
          * 平行四边形的判定
        * 特殊的平行四边形
          * 矩形
            * 矩形的性质
            * 矩形的判定
          * 菱形
            * 菱形的性质
            * 菱形的判定
          * 正方形
            * 正方形的性质
            * 正方形的判定
        * 梯形
          * 梯形
            * 梯形的性质
            * 梯形的判定
          * 等腰梯形
            * 等腰梯形的性质
            * 等腰梯形的判定
          * 三角形、梯形的中位线
            * 三角形的中位线
            * 梯形的中位线
    * 圆
      * 圆的基本性质
        * 圆的确定
        * 圆心角、弧、弦、弦心距之间的关系
        * 垂径定理
        * 圆周角
      * 圆的位置关系
        * 点与圆的位置关系
        * 直线与圆的位置关系
        * 圆与圆的位置关系
      * 直线与圆
        * 圆的切线
        * 与圆有关的角及其比例线段
          * 与圆有关的角
          * 与圆有关的比例线段
        * 圆内接四边形
      * 正多边形与圆
      * 弧长和扇形面积
      * 圆锥的侧面积
  * 几何变换
    * 平移
    * 轴对称
      * 轴对称
        * 轴对称的概念
        * 线段的垂直平分线
      * 轴对称图形
      * 等腰三角形
        * 等腰三角形
        * 等边三角形
      * 最短路径问题
    * 旋转
      * 图形的旋转
      * 中心对称
        * 中心对称的定义
        * 中心对称图形
        * 关于原点对称的点的坐标
      * 旋转对称
    * 翻折
  * 解析几何
  * 向量几何

**Comment by dangming25** [comment]
以上是初中的几何

**Comment by mathedu4all** [comment]
已提交.
